[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
code = "9NUNPJkj84yTh85kmUfZXGsN2iri5aj8CAYBcUQPgdxN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/buchetinagapadmini/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
